* __INSTRUCTIONS:__


    * Add your code as indicated in each cell.


    * Besides adding your code, do not alter this file.


    * Do not delete or change test cases. Once you are done with the assignment, you can run the test cases to see if you programmed the questions correctly.


    * If you get a question wrong, do not give up. Keep trying until you pass the test cases.


    * Rename the file as firstname_lastname_assignmentid.ipynb (e.g., marina_johnson_assignment1.ipynb)


    * Only submit .ipynb files (no .py files)

# Question 1
1. Read the ckd dataset (ckd.xlsx) and save it as df_ckd


2. Read the AAPL dataset (AAPL.csv) and save it as df_aapl


3. Read the telco_churn dataset (telco_churn.csv) and save it as df_churn

    * __Hints:__
        * Check __Module 3__ videos. Particularly, check __Module3b: Pandas Intro_
        * Ensure the file is in the same folder with this assignment file.
        * Do not use any path to read the dataset. For example, I should not be using __"/Users/armej/Downloads/ckd.xlsx".__ If you use a path, I will not be able to run your and grade code.

In [ ]:
import pandas as pd

df_ckd =  pd.read_excel('ckd.xlsx')
df_appl =  pd.read_csv('AAPL.csv')
df_churn = pd.read_csv('telco_churn.csv')

## Test case for Question 1. Do not alter or delete the cell below.

In [ ]:
score = dict()

try:
    if (df_churn.size == 147903 and df_appl.size == 1288 and df_ckd.size == 9675):
        score['question 1'] = 'pass'
    else:
        score['question 1'] = 'fail'
except:
    score['question 1'] = 'fail'

In [ ]:
score

{'question 1': 'pass'}

#############################################################################

# Question 2

1. Identify the names of numerical variables for the ckd (chronic kidney disease) dataset.


2. Identify the names of categorical variables for the ckd (chronic kidney disease) dataset.

    * __Hints:__
        * Check __Module 3__ videos. Particularly, look at the __Module 3b: Pandas Intro__ (The solution is illustrated around __minute 16 to minute 20__ in Module 3b: Pandas Intro)
        * Do not forget the make the result a __LIST__. So numerical_var and categorical_var must be a list

In [ ]:
numerical_var = df_ckd.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_var = df_ckd.select_dtypes(include=['object']).columns.tolist()

## Test case for Question 2. Do not alter or delete the cell below.

In [ ]:
try:
    if ((numerical_var == ['age', 'bp','sg','al','su','bgr','bu','sc','sod', 'pot','hemo','pcv','wbcc','rbcc']) & (categorical_var == ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class'])):
        score['question 2'] = 'pass'
    else:
        score['question 2'] = 'fail'
except:
    score['question 2'] = 'fail'

In [ ]:
score

{'question 1': 'pass', 'question 2': 'pass'}

#############################################################################

# Question 3

1. How many people have __wbcc__ less than or equal to 7000?

    * __Hints:__
        * You will filter the dataframe using only the __wbcc__ column.
        * The filtered dataframe should only contain instances whose __wbcc is less than or equal to 7000.__
        * After you filter your dataset, do not forget the count the number of observations.
        * Check __Module 3c: Accessing columns and rows__
        
        
2. How many people with ckd have wbcc less than 6000?

    * __Hints:__
        * You will filter the dataframe using two columns: __wbcc and class__ columns.
        * The filtered dataframe should only contain instances whose __wbcc is less than 6000, and class is equal to "ckd".__
        * After you filter your dataset, do not forget the count the number of observations.
        * Check __Module 3c: Accessing columns and rows__

In [ ]:
ppl_with_low_wbcc =  df_ckd[df_ckd['wbcc'] <= 7000].shape[0]
ckd_ppl_with_low_wbcc = df_ckd[(df_ckd['wbcc'] < 6000) & (df_ckd['class'] == 'ckd')].shape[0]

## Test case for Question 3. Do not alter or delete the cell below.

In [ ]:
try:
    if ((ppl_with_low_wbcc == 104) and (ckd_ppl_with_low_wbcc == 25)):
        score['question 3'] = 'pass'
    else:
        score['question 3'] = 'fail'
except:
    score['question 3'] = 'fail'

In [ ]:
score

{'question 1': 'pass', 'question 2': 'pass', 'question 3': 'pass'}

#############################################################################

# Question 4

1. How many people who are less than or equal to 60 years old have ckd (chronic kidney disease).

    * __Hints:__
        * You will filter the dataframe using two columns: __age and class__ columns.
        * The filtered dataframe should only contain instances whose __age is less than or equal to 60 years and class is equal to "ckd".__
        * After you filter your dataset, do not forget the count the number of observations.
        * Check __Module 3c: Accessing columns and rows__

In [ ]:
ckd_ppl_less_60 = df_ckd[(df_ckd['age'] <= 60) & (df_ckd['class'] == 'ckd')].shape[0]

## Test case for Question 4. Do not alter or delete the cell below.

In [ ]:
try:
    if ckd_ppl_less_60 == 130:
        score['question 4'] = 'pass'
    else:
        score['question 4'] = 'fail'
except:
    score['question 4'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass'}

#############################################################################

# Question 5

1. What is the interquartile range of the __age__ column for the people with ckd?

    * __Hints:__
        * Interquartile range is the difference between the 75th percentile and 25th percentile.
        * First, filter the data using a column: __class.__ The filtered dataset should only contain observations where __class is equal to "ckd".__
        * You will then need to select the __age__ column in the filtered dataset and compute its 75th percentile.
        * You will repeat the same steps to compute the 25th percentile.
        * Finally, take the difference between the 75th and 25th percentile.
        * Check __Module 3c: Accessing columns and rows__ and __Module 3d: Desriptive Statistics__
    
    
2. What is the interquartile range of the __age__ column for the people without ckd?

     * __Hints:__
        * Interquartile range is the difference between the 75th percentile and 25th percentile.
        * First, filter the data using a column: __class.__ The filtered dataset should only contain observations where __class is equal to "notckd".__
        * You will then need to select the __age__ column in the filtered dataset and compute its 75th percentile.
        * You will repeat the same steps to compute the 25th percentile.
        * Finally, take the difference between the 75th and 25th percentile.
        * Check __Module 3c: Accessing columns and rows__ and __Module 3d: Desriptive Statistics__

In [ ]:
ckd_data = df_ckd[df_ckd['class'] == 'ckd']
age_75th_percentile_ckd = ckd_data['age'].quantile(0.75)
age_25th_percentile_ckd = ckd_data['age'].quantile(0.25)
iqr_ckd = age_75th_percentile_ckd - age_25th_percentile_ckd

notckd_data = df_ckd[df_ckd['class'] == 'notckd']
age_75th_percentile_notckd = notckd_data['age'].quantile(0.75)
age_25th_percentile_notckd = notckd_data['age'].quantile(0.25)
iqr_notckd = age_75th_percentile_notckd - age_25th_percentile_notckd

## Test case for Question 5. Do not alter or delete the cell below.

In [ ]:
try:
    if ((iqr_ckd == 17.5) and (iqr_notckd == 24)):
        score['question 5'] = 'pass'
    else:
        score['question 5'] = 'fail'
except:
    score['question 5'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass'}

#############################################################################################

__QUESTIONS 6, 7, & 8 USE THE APPL.CSV dataset (df_appl)__

#############################################################################################

# Question 6

1. Compute the average __Volume__ for April in the year of 2015

    * __Hints:__
        * You will need to filter the dataset in a way that your dataset will only contain 2015 April observations.
        * Remember __Date__ column contains the month, day, and year information. Split this column into these three elements. For example, '04/27/2020' should be split into ['04','27', '2020']. The first element is the month, the second element is the day, and third element is the year. You will need to access and retrieve the first and the third elements.
        * Access the months in the Date column after splitting it. Assign the months you obtained to this newly created __month__ column.
        * Access the years in the Date column after splitting it. Assign the years you obtained to this newly created __year__ column.
        * Now your dataset has two extra columns: __month and year.__ Use these columns to filter your dataset.
        * Your filtered dataset should have __month equal to 04 and year equal to 2015__.
        * You can select the __Volume__ column from this filtered data and compute its average.
        * Check __Module 3c: Accessing Columns and Rows__, __Module 3d: Descriptive Statistics__ and __Module 3g: Summary and Aggregation__, and __Module 1e: String operations__. You may need to use a function such as split.

In [ ]:
df_appl[['month', 'day', 'year']] = df_appl['Date'].str.split('/', expand=True)
df_appl['month'] = df_appl['month'].astype(int)
df_appl['year'] = df_appl['year'].astype(int)
filtered_data = df_appl[(df_appl['month'] == 4) & (df_appl['year'] == 2015)]
average_vol_april_2015 = filtered_data['Volume'].mean()
average_vol_april_2015

245451650.0

## Test case for Question 6. Do not alter or delete the cell below.

In [ ]:
try:
    if ((average_vol_april_2015 > 245451649) and (average_vol_april_2015 < 245451651)):
        score['question 6'] = 'pass'
    else:
        score['question 6'] = 'fail'
except:
    score['question 6'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass'}

#############################################################################

# Question 7

1. Compute the correlation between __Volume__ and closing price (__Close__) for the year of 2016

    * __Hints:__
        * You have already created the year and month columns in the previous question.
        * Filter the dataset by using the __year__ column. Select the observations in a way that __year is equal to 2016.__
        * Then, select Volume and Close columns in the filtered dataset to compute the corrrelation.
        * Remember .corr() function will give you a 2 by 2 correlation matrix. So access the correlation from the matrix by slicing the matrix. (you will need to access the first row, first column)
        * Check __Module 3c: Accessing Columns and Rows__, __Module 3d: Descriptive Statistics__ also check the website https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html

In [ ]:
filtered_data_2016 = df_appl[df_appl['year'] == 2016]
corr_vol_price = filtered_data_2016['Volume'].corr(filtered_data_2016['Close'])

corr_vol_price

-0.3317076392638936

## Test case for Question 7. Do not alter or delete the cell below.

In [ ]:
try:
    if ((corr_vol_price  < -0.329) and (corr_vol_price > -0.34)):
        score['question 7'] = 'pass'
    else:
        score['question 7'] = 'fail'
except:
    score['question 7'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass'}

#############################################################################

# Question 8

1. What is the average fluctuation (i.e., difference) between the closing (Close) and opening (Open) prices?


2. What is the standard deviation of the fluctuations (i.e., difference) between the closing (Close) and opening (Open) prices?

    * __Hints__:
        * Create a new column as the difference between opening costs (__Open__) and closing costs (__Close__). All you need to do is to select these columns in the dataset and take the difference using the minus - sign.
        * Name this column as diff
        * You can compute the average and standard deviation of this new column using the mean() and std() functions.
        * Check __Module 3d: Descriptive Statistics__

In [ ]:
 df_appl['diff'] =  df_appl['Close'] - df_appl['Open']
average_diff =   df_appl['diff'].mean()
stdev_diff =  df_appl['diff'].std()

## Test case for Question 8. Do not alter or delete the cell below.

In [ ]:
try:
    if ((stdev_diff  > 4.20) and (stdev_diff < 4.3)):
        score['question 8'] = 'pass'
    else:
        score['question 8'] = 'fail'
except:
    score['question 8'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass'}

#############################################################################################

__QUESTIONS 9, 10, 11 & 12 USE THE TELCO_CHURN.CSV dataset (df_churn)__

#############################################################################################

# Question 9

1. What is the average tenure of churned customers?


2. What is the average tenure of not churned customers?

    * __Hints:__
      * To compute the average __tenure__ for churned customers, first filter the dataset using the __Churn__ column where __Churn is Yes.__
      * In this filtered dataset, select the __tenure__ column and compute its average.
      * Repeat the same steps for non churned customers (__Churn is equal to No__)
      * Check __Module 3c: Accessing Columns and Rows__ and __Module 3d: Descriptive Statistics__

In [ ]:
churned_customers = df_churn[df_churn['Churn'] == 'Yes']
average_tenure_churn = churned_customers['tenure'].mean()


not_churned_customers = df_churn[df_churn['Churn'] == 'No']
average_tenure_not_churn = not_churned_customers['tenure'].mean()

## Test case for Question 9. Do not alter or delete the cell below.

In [ ]:
try:
    if (average_tenure_churn > 17.9 and average_tenure_churn < 18 and average_tenure_not_churn > 37.5 and average_tenure_not_churn < 37.8):
        score['question 9'] = 'pass'
    else:
        score['question 9'] = 'fail'
except:
    score['question 9'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass'}

#############################################################################

# Question 10

1. What is the average tenure of customers where StreamingTV is No?


2. What is the average tenure of customers where StreamingTV is Yes?

    * __Hints:__
      * To compute the average __tenure__ for people with __StreamingTV is No__, first filter the dataset using the __StreamingTV__ column where __StreamingTV is No__.
      * In this filtered dataset, select the __tenure__ column and compute its average.
      * Repeat the same steps for StreamingTV is Yes (____StreamingTV is Yes__)
      * Check __Module 3c: Accessing Columns and Rows__ and __Module 3d: Descriptive Statistics__

In [ ]:
no_streamingTV_customers = df_churn[df_churn['StreamingTV'] == 'No']
average_tenure_not_streamingTV = no_streamingTV_customers['tenure'].mean()

streamingTV_customers = df_churn[df_churn['StreamingTV'] == 'Yes']
average_tenure_streamingTV = streamingTV_customers['tenure'].mean()

## Test case for Question 10. Do not alter or delete the cell below.

In [ ]:
try:
    if (average_tenure_not_streamingTV > 24.5 and average_tenure_not_streamingTV < 25.5 and average_tenure_streamingTV > 40.5 and average_tenure_streamingTV < 41.5):
        score['question 10'] = 'pass'
    else:
        score['question 10'] = 'fail'
except:
    score['question 10'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass',
 'question 10': 'pass'}

#############################################################################

# Question 11

1. Use the PaymentMethod column and create a new column named AutoPayment. If the PaymentMethod has the word automatic, make the values in this column 1. Otherwise, make its values 0.

    * __Hints__:
        * You will iterate through each observation in the __PaymentMethod__ column to check if that particular observation has the word automatic.
        * If yes, assign 1 to this newly created column. Otherwise, assign 0.
        * This column will tell us if customers do automatic payment.
        * Check __Module 1e: String operations__. You may need to use a function such as find(). Also check __Module 2b: for loops__ and __Module 2e: Conditional Statements__

In [ ]:
df_churn['AutoPayment'] = df_churn['PaymentMethod'].apply(lambda x: 1 if 'automatic' in x.lower() else 0)

## Test case for Question 11. Do not alter or delete the cell below.

In [ ]:
try:
    if df_churn['AutoPayment'].sum() == 3066:
        score['question 11'] = 'pass'
    else:
        score['question 11'] = 'fail'
except:
    score['question 11'] = 'fail'

In [ ]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass',
 'question 10': 'pass',
 'question 11': 'pass'}

#############################################################################

# Question 12

* What percentage of people with autopayment churn?


* What percentage of people without autopayment churn?

    * __Hints__:
        * You will use the new column you created in Question 11.
        * We will find the numerator. This is basically the number of people who do __autopayment and have churned__. Filter the dataset using the __Churn and AutoPayment__ columns. (__Churn is equal to Yes, and Autopayment is equal to 1__). Count the number of observations in this filtered dataset. This is the numerator.
        * We will find the denominator. This is basically the number of people who make Autopayment. Filter the dataset using the __Autopayment__ column (__Autopayment is equal to 1__). Count the number of observations in this filtered dataset. This is the denominator.
        * You can divide the numerator by the denominator.   
        * For the second part of the question, repeat the similar steps. This time, you will select people who did not do __Autopayment__ (__Autopayment is equal to 0__).

In [ ]:
numerator_autopay = len(df_churn[(df_churn['AutoPayment'] == 1) & (df_churn['Churn'] == 'Yes')])
denominator_autopay = len(df_churn[df_churn['AutoPayment'] == 1])
percent_churn_autopay = (numerator_autopay / denominator_autopay) * 100

numerator_noautopay = len(df_churn[(df_churn['AutoPayment'] == 0) & (df_churn['Churn'] == 'Yes')])
denominator_noautopay = len(df_churn[df_churn['AutoPayment'] == 0])
percent_churn_noautopay = (numerator_noautopay / denominator_noautopay) * 100

percent_churn_autopay, percent_churn_noautopay

(15.981735159817351, 34.674377671611765)

## Test case for Question 12. Do not alter or delete the cell below.

In [ ]:
try:
    if (percent_churn_autopay > 15.5 and percent_churn_autopay < 16.5 and percent_churn_noautopay > 34.5 and percent_churn_noautopay < 35.5):
        score['question 12'] = 'pass'
    else:
        score['question 12'] = 'fail'
except:
    score['question 12'] = 'fail'

In [59]:
score

{'question 1': 'pass',
 'question 2': 'pass',
 'question 3': 'pass',
 'question 4': 'pass',
 'question 5': 'pass',
 'question 6': 'pass',
 'question 7': 'pass',
 'question 8': 'pass',
 'question 9': 'pass',
 'question 10': 'pass',
 'question 11': 'pass',
 'question 12': 'pass'}

#############################################################################

# Total Score

In [58]:
total_score = 0
for i in list(score.values()):
    if i=='pass':
        total_score = total_score + 8.34
print('your total score is: ', round(total_score))

your total score is:  100